name: ci

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@main

      - name: Print mage digest
        run: echo ${{ steps.set_version.outputs.version }}
