name: ci

on:
  push:
    branches:
      - main
      - 'releases/**'

permissions:
  contents: write
  repository-projects: write
  packages: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-20.04



    steps:
      -
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@main

        with:
          primary_branch: main
          enable_github_releases: true
          release_tag_prefix: "v"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: Generated version
        run: echo ${{ steps.set_version.outputs.version }}
      -
        name: Safe version
        run: echo ${{ steps.set_version.outputs.safe_version }}
      -
        name: Java version
        run: echo ${{ steps.set_version.outputs.java_version }}
