name: ci

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set application version
        uses: kvendingoldo/semver-action@dbea13fa1da0d5f38ef587bdbb513258a7dd0c09

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
